FROM nginx:1.23
COPY /dashboard/nginx.conf /etc/nginx/nginx.conf
COPY /dashboard/dashboard.tar.gz /usr/share/nginx/html
RUN cd /usr/share/nginx/html && tar zxvf ./dashboard.tar.gz && rm ./dashboard.tar.gz
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
